repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff-check
        args: [--fix]
        files: ^api/
      - id: ruff-format
        files: ^api/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier
        language: node
        files: ^ui/app/
        args: [--write, --config, ui/app/.prettierrc, --ignore-path, ui/app/.prettierignore]
        additional_dependencies:
          - prettier@3.3.3
          - prettier-plugin-tailwindcss@0.6.8
