services:
  ui:
    ports:
      # We should use the same port internally and externally, otherwise the dev tools support
      # of the browser is for almost nothing
      - "8077:8077"
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run dev -- --host 0.0.0.0
    # use this only if you need to keep the container running but do not want to start the frontend application
    # command: bash -c 'while true; do sleep 5; done'
    restart: unless-stopped
    depends_on:
      - api
  api:
    build:
      args:
        DCC_ENV: "dev"
    environment:
      - DJANGO_DEBUG=True
    ports:
      - 5077:5000
  db:
    ports:
      - "54377:5432"
  mkdocs:
    build:
      context: docs
      dockerfile: Dockerfile
    ports:
      - "8078:8000"
    volumes:
      - ./docs/:/docs/:z
