version: "3"

services:
  ui:
    ports:
      # We should use the same port internally and externally, otherwise the dev tools support
      # of the browser is for almost nothing
      - "8077:8077"
    command:
      - /bin/sh
      - -c
      - |
        yarn
        yarn dev --host 0.0.0.0 --port 8077
    # use this only if you need to keep the container running but do not want to start the frontend application
    # command: bash -c 'while true; do sleep 5; done'
    restart: unless-stopped
    depends_on:
      - api
  api:
    environment:
      - DJANGO_DEBUG=True
    ports:
      - 5077:5000
  db:
    ports:
      - "54377:5432"
