# Generated by Django 5.1.15 on 2026-01-09 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_author_date_of_death"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["id"]},
        ),
    ]
