# Generated by Django 6.0.8 on 2026-09-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_book_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("respondent_name", models.CharField(blank=True, max_length=200)),
                ("respondent_email", models.EmailField(db_index=True, max_length=254)),
                ("provider_name", models.CharField(db_index=True, max_length=200)),
                ("solution_name", models.CharField(db_index=True, max_length=200)),
                (
                    "hospital_wide_cis",
                    models.BooleanField(
                        default=False, verbose_name="A. Hospital-wide clinical information system"
                    ),
                ),
                (
                    "patient_administration",
                    models.BooleanField(
                        default=False,
                        verbose_name="B. Patient administration / hospital management",
                    ),
                ),
                (
                    "specialized_clinical",
                    models.BooleanField(
                        default=False, verbose_name="C. Specialized clinical solution / modules"
                    ),
                ),
                (
                    "data_interoperability",
                    models.BooleanField(
                        default=False, verbose_name="D. Data / interoperability solution"
                    ),
                ),
                (
                    "patient_facing",
                    models.BooleanField(default=False, verbose_name="E. Patient-facing solution"),
                ),
                (
                    "questionnaire_version",
                    models.PositiveSmallIntegerField(default=1, editable=False),
                ),
                (
                    "answers",
                    models.JSONField(
                        help_text="Questionnaire answers keyed by question identifier."
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-submitted_at", "-pk"],
            },
        ),
    ]
