# Generated by Django 6.0.8 on 2026-09-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questionnaire_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='submission_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
