# Generated by Django 6.0.8 on 2026-09-18 13:05

import json

from django.db import migrations, models


# Frozen mapping: migrations must not depend on the live questionnaire definition.
QUESTION_FIELDS = {
    "apiAccess": "api_access",
    "apiTypes": "api_types",
    "standards": "interoperability_standards",
    "deployment": "deployment_models",
    "structure": "data_structure",
    "coding": "clinical_coding",
    "archive": "document_archive",
    "export": "record_export",
    "exportDetails": "record_export_details",
    "security": "security_capabilities",
    "switzerland": "swiss_data_residency",
    "roadmap": "roadmap_involvement",
    "configuration": "configuration_options",
    "transition": "exit_provisions",
    "rights": "content_rights",
    "pricing": "pricing_model",
    "costs": "cost_components",
    "term": "contract_term",
    "exitCosts": "exit_costs",
    "reporting": "reporting_access",
    "research": "research_capabilities",
    "secondary": "secondary_use_governance",
    "clinicalCapabilities": "clinical_capabilities",
    "specialties": "clinical_specialties",
    "documentation": "documentation_support",
    "dataCapabilities": "data_capabilities",
    "architecture": "architecture_role",
    "dataIndependent": "data_independence",
    "patientFunctions": "patient_functions",
    "languages": "patient_languages",
    "aggregation": "patient_aggregation",
    "writeBack": "patient_write_back",
    "patientIndependent": "patient_independence",
    "parties": "implementation_parties",
    "rollout": "rollout_approaches",
    "migration": "migration_approach",
    "goLive": "go_live_services",
    "requirements": "integration_requirements",
}


def move_answers_to_columns(apps, schema_editor):
    response_model = apps.get_model("core", "QuestionnaireResponse")
    for response in response_model.objects.using(schema_editor.connection.alias).iterator():
        unknown = set(response.answers) - QUESTION_FIELDS.keys()
        if unknown:
            raise ValueError(f"Cannot migrate unrecognized questions: {sorted(unknown)}")
        for question_id, answer in response.answers.items():
            if not isinstance(answer, dict):
                value = json.dumps(answer, ensure_ascii=False)
            elif answer.get("readable_answer"):
                value = "\n".join(answer["readable_answer"])
            elif answer.get("text"):
                value = answer["text"]
            elif any(answer.get(key) for key in ("selected", "details", "rows")):
                value = json.dumps(answer, ensure_ascii=False)
            else:
                value = ""
            setattr(response, QUESTION_FIELDS[question_id], value)
        response.save(
            using=schema_editor.connection.alias, update_fields=list(QUESTION_FIELDS.values())
        )


def restore_answers_object(apps, schema_editor):
    response_model = apps.get_model("core", "QuestionnaireResponse")
    for response in response_model.objects.using(schema_editor.connection.alias).iterator():
        response.answers = {
            question_id: {
                "question": question_id,
                "selected": [],
                "text": value,
                "details": {},
                "rows": {},
                "readable_answer": value.splitlines(),
            }
            for question_id, field in QUESTION_FIELDS.items()
            if (value := getattr(response, field)) is not None
        }
        response.save(using=schema_editor.connection.alias, update_fields=["answers"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_questionnaire_submission_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaireresponse",
            name="api_access",
            field=models.TextField(blank=True, null=True, verbose_name="1.1 API access"),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="api_types",
            field=models.TextField(blank=True, null=True, verbose_name="1.1 Documented API types"),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="architecture_role",
            field=models.TextField(
                blank=True, null=True, verbose_name="2.1 Role in hospital IT architecture"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="clinical_capabilities",
            field=models.TextField(
                blank=True, null=True, verbose_name="2.1 Clinical functional areas"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="clinical_coding",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.2 Clinical coding standards"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="clinical_specialties",
            field=models.TextField(blank=True, null=True, verbose_name="2.1 Clinical specialties"),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="configuration_options",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.3 Customer-specific configuration"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="content_rights",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.3 Configuration and content rights"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="contract_term",
            field=models.TextField(blank=True, null=True, verbose_name="1.4 Initial contract term"),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="cost_components",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.4 Included and additional costs"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="data_capabilities",
            field=models.TextField(
                blank=True, null=True, verbose_name="2.1 Data / interoperability capabilities"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="data_independence",
            field=models.TextField(
                blank=True, null=True, verbose_name="2.1 Data solution independent of CIS"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="data_structure",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.2 Clinical data structure"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="deployment_models",
            field=models.TextField(blank=True, null=True, verbose_name="1.1 Deployment models"),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="document_archive",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.2 Long-term document and image storage"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="documentation_support",
            field=models.TextField(
                blank=True, null=True, verbose_name="2.1 Documentation burden reduction"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="exit_costs",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.4 Termination and switching costs"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="exit_provisions",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.3 Exit and transition provisions"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="go_live_services",
            field=models.TextField(
                blank=True, null=True, verbose_name="2.3 Change management and go-live services"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="implementation_parties",
            field=models.TextField(
                blank=True, null=True, verbose_name="2.3 Implementation parties"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="integration_requirements",
            field=models.TextField(
                blank=True, null=True, verbose_name="2.3 Integration requirements"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="interoperability_standards",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.1 Interoperability standards"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="migration_approach",
            field=models.TextField(blank=True, null=True, verbose_name="2.3 Migration approach"),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="patient_aggregation",
            field=models.TextField(
                blank=True, null=True, verbose_name="2.1 Multi-system patient information"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="patient_functions",
            field=models.TextField(
                blank=True, null=True, verbose_name="2.1 Patient-facing functions"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="patient_independence",
            field=models.TextField(
                blank=True, null=True, verbose_name="2.1 Patient solution independent of CIS"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="patient_languages",
            field=models.TextField(
                blank=True, null=True, verbose_name="2.1 Patient-facing languages"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="patient_write_back",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="2.1 Patient information written back to clinical systems",
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="pricing_model",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.4 Licence / subscription pricing"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="record_export",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.2 Complete clinical record export"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="record_export_details",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.2 Export limitations and dependencies"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="reporting_access",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.5 Reporting and analysis access"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="research_capabilities",
            field=models.TextField(blank=True, null=True, verbose_name="1.5 Research capabilities"),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="roadmap_involvement",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.3 Customer roadmap involvement"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="rollout_approaches",
            field=models.TextField(blank=True, null=True, verbose_name="2.3 Rollout approaches"),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="secondary_use_governance",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.5 Secondary-use governance"
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="security_capabilities",
            field=models.TextField(blank=True, null=True, verbose_name="1.2 Security capabilities"),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="swiss_data_residency",
            field=models.TextField(
                blank=True, null=True, verbose_name="1.2 Switzerland-only data storage"
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireresponse",
            name="provider_name",
            field=models.CharField(db_index=True, max_length=200, verbose_name="Company"),
        ),
        migrations.AlterField(
            model_name="questionnaireresponse",
            name="answers",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(move_answers_to_columns, restore_answers_object),
        migrations.RemoveField(model_name="questionnaireresponse", name="answers"),
    ]
