# Generated by Django 6.0.8 on 2026-09-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_questionnaire_answer_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='solution_name',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
