# Generated by Django 6.0.8 on 2026-09-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_questionnaire_version_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='aggregation_methods',
            field=models.TextField(blank=True, null=True, verbose_name='2.1 Multi-system patient information'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='app_integration_standards',
            field=models.TextField(blank=True, null=True, verbose_name='1.1 Application integration standards'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='clinical_data_models',
            field=models.TextField(blank=True, null=True, verbose_name='1.2 Clinical data models'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='clinical_terminologies',
            field=models.TextField(blank=True, null=True, verbose_name='1.2 Clinical terminologies and coding'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='developer_independence',
            field=models.TextField(blank=True, null=True, verbose_name='1.1 Independent integration development'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='developer_resources',
            field=models.TextField(blank=True, null=True, verbose_name='1.1 Developer resources'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='documentation_methods',
            field=models.TextField(blank=True, null=True, verbose_name='2.1 Documentation burden reduction'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='implementation_involvement',
            field=models.TextField(blank=True, null=True, verbose_name='2.3 Implementation involvement'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='reporting_methods',
            field=models.TextField(blank=True, null=True, verbose_name='1.5 Reporting and analysis access'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='structured_information_types',
            field=models.TextField(blank=True, null=True, verbose_name='1.2 Structured clinical information types'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='third_party_approval',
            field=models.TextField(blank=True, null=True, verbose_name='1.3 Third-party application approval'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='third_party_integration',
            field=models.TextField(blank=True, null=True, verbose_name='1.1 Third-party application integration'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='questionnaire_version',
            field=models.PositiveSmallIntegerField(default=5, editable=False),
        ),
    ]
