# Generated by Django 6.0.8 on 2026-09-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_questionnaireresponse_aggregation_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='clinical_data_management',
            field=models.TextField(blank=True, null=True, verbose_name='1.2 Clinical information management'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='data_retention',
            field=models.TextField(blank=True, null=True, verbose_name='1.2 Patient information retained'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='external_integration',
            field=models.TextField(blank=True, null=True, verbose_name='1.2 External integration support'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='questionnaire_version',
            field=models.PositiveSmallIntegerField(default=6, editable=False),
        ),
    ]
