# Generated by Django 6.0.8 on 2026-09-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_questionnaireresponse_clinical_data_management_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='questionnaire_version',
            field=models.PositiveSmallIntegerField(default=7, editable=False),
        ),
    ]
