# Generated by Django 6.0.8 on 2026-10-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_questionnaireresponse_questionnaire_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='questionnaire_version',
            field=models.PositiveSmallIntegerField(default=8, editable=False),
        ),
    ]
