# Generated by Django 6.0.8 on 2026-10-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_questionnaireresponse_questionnaire_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='certification_details',
            field=models.TextField(blank=True, null=True, verbose_name='1.3 Certificate scope and validity'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='certifications',
            field=models.TextField(blank=True, null=True, verbose_name='1.3 Certifications and conformity'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='interoperability_testing',
            field=models.TextField(blank=True, null=True, verbose_name='1.1 Swiss interoperability testing'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='questionnaire_version',
            field=models.PositiveSmallIntegerField(default=9, editable=False),
        ),
    ]
