# Generated by Django 6.0.8 on 2026-10-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_questionnaireresponse_certification_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='data_exchange_handling',
            field=models.TextField(blank=True, null=True, verbose_name='2.6 Exchanged data handling'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='patient_exchange',
            field=models.TextField(blank=True, null=True, verbose_name='2.7 Patient solution data exchange'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='questionnaire_version',
            field=models.PositiveSmallIntegerField(default=10, editable=False),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='solution_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
