# Generated by Django 6.0.8 on 2026-10-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_questionnaireresponse_data_exchange_handling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=200, unique=True)),
                ('declined', models.BooleanField(default=False, help_text='Mark this only when the vendor explicitly declined. An invited vendor without a submission or decline counts as no response.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Invited vendor',
                'verbose_name_plural': 'Invited vendors',
                'ordering': ['provider_name'],
            },
        ),
    ]
