# Generated by Django 6.0.8 on 2026-10-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_questionnaire_version_11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='data_interoperability',
            field=models.BooleanField(default=False, verbose_name='C. Data / interoperability solution'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='patient_administration',
            field=models.BooleanField(default=False, verbose_name='Legacy patient administration / hospital management'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='patient_facing',
            field=models.BooleanField(default=False, verbose_name='D. Patient-facing solution'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='questionnaire_version',
            field=models.PositiveSmallIntegerField(default=12, editable=False),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='specialized_clinical',
            field=models.BooleanField(default=False, verbose_name='B. Specialized clinical solution / modules'),
        ),
    ]
