# Generated by Django 6.0.8 on 2026-10-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_questionnaireresponse_questionnaire_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorinvitation",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="vendorinvitation",
            name="invitation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorinvitation",
            name="invitation_sent_by",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
