# Generated by Django 6.0.8 on 2026-10-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_vendorinvitation_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaireresponse",
            name="imported_pdf",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="imported_pdf_name",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="imported_pdf_sha256",
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
    ]
